export const REQUEST_START = "REQUEST_START";

export const GET_BLOCKS_SUCCESS = "GET_BLOCKS_SUCCESS";
export const CREATE_BLOCK_SUCCESS = "CREATE_BLOCK_SUCCESS";
export const UPDATE_BLOCK_SUCCESS = "UPDATE_BLOCK_SUCCESS";
export const DELETE_BLOCK_SUCCESS = "DELETE_BLOCK_SUCCESS";

export const GET_STYLES_SUCCESS = "GET_STYLES_SUCCESS";
export const UPDATE_STYLES_SUCCESS = "UPDATE_STYLES_SUCCESS";
export const GET_BLOCK_STYLES_SUCCESS = "GET_BLOCK_STYLES_SUCCESS";

export const REQUEST_FAILURE = "REQUEST_FAILURE";
export const CLEAN_ERROR = "CLEAN_ERROR";
